INSERT INTO majmin (id, name, type, classesNeeded) VALUES (26, 'Creative Writing', 'minor', 'Creative Writing Fiction, Creative Writing Poetry');
INSERT INTO majmin (id, name, type, classesNeeded) VALUES (27, 'Film Studies', 'minor', 'Introduction to Film Studies, Film History');
INSERT INTO majmin (id, name, type, classesNeeded) VALUES (28, 'Spanish', 'minor', 'Intermediate Spanish, Spanish Conversation and Composition');
INSERT INTO majmin (id, name, type, classesNeeded) VALUES (29, 'Human Resource Management', 'minor', 'Human Resource Management, Organizational Behavior');
INSERT INTO majmin (id, name, type, classesNeeded) VALUES (30, 'Public Health', 'minor', 'Introduction to Public Health, Health Policy and Administration');
INSERT INTO majmin (id, name, type, classesNeeded) VALUES (31, 'Entrepreneurship', 'minor', 'Entrepreneurship and Innovation, Business Planning');
INSERT INTO majmin (id, name, type, classesNeeded) VALUES (32, 'Statistics', 'minor', 'Probability and Statistics, Statistical Methods');
INSERT INTO majmin (id, name, type, classesNeeded) VALUES (33, 'Art History', 'minor', 'Survey of Western Art, Modern Art');
INSERT INTO majmin (id, name, type, classesNeeded) VALUES (34, 'French', 'minor', 'Intermediate French, French Conversation and Composition');
INSERT INTO majmin (id, name, type, classesNeeded) VALUES (35, 'Environmental Studies', 'minor', 'Introduction to Environmental Studies, Environmental Policy');
INSERT INTO majmin (id, name, type, classesNeeded) VALUES (36, 'Religious Studies', 'minor', 'World Religions, Religious Ethics');
INSERT INTO majmin (id, name, type, classesNeeded) VALUES (37, 'Information Technology', 'minor', 'Introduction to Information Systems, Database Management');
INSERT INTO majmin (id, name, type, classesNeeded) VALUES (38, 'Womens Studies', 'minor', 'Introduction to Womens Studies, Gender and Society');
INSERT INTO majmin (id, name, type, classesNeeded) VALUES (39, 'Linguistics', 'minor', 'Introduction to Linguistics, Phonetics and Phonology');
INSERT INTO majmin (id, name, type, classesNeeded) VALUES (40, 'Philosophy of Science', 'minor', 'Philosophy of Science, History of Science');
INSERT INTO majmin (id, name, type, classesNeeded) VALUES (41, 'Theater Arts', 'minor', 'Acting, Theater Production');
INSERT INTO majmin (id, name, type, classesNeeded) VALUES (42, 'Ethnic Studies', 'minor', 'Introduction to Ethnic Studies, Race, Ethnicity, and Identity');
INSERT INTO majmin (id, name, type, classesNeeded) VALUES (43, 'Geology', 'minor', 'Physical Geology, Historical Geology');
INSERT INTO majmin (id, name, type, classesNeeded) VALUES (44, 'Museum Studies', 'minor', 'Introduction to Museum Studies, Museum Collections Management');
INSERT INTO majmin (id, name, type, classesNeeded) VALUES (45, 'Sports Management', 'minor', 'Introduction to Sports Management, Sports Marketing');
INSERT INTO majmin (id, name, type, classesNeeded) VALUES (46, 'African American Studies', 'minor', 'Introduction to African American Studies, African American History');
INSERT INTO majmin (id, name, type, classesNeeded) VALUES (47, 'Sustainability Studies', 'minor', 'Introduction to Sustainability, Sustainable Resource Management');
INSERT INTO majmin (id, name, type, classesNeeded) VALUES (48, 'Cybersecurity', 'minor', 'Cybersecurity Fundamentals, Network Security');
INSERT INTO majmin (id, name, type, classesNeeded) VALUES (49, 'Political Philosophy', 'minor', 'Political Philosophy, Ethics and Public Policy');
INSERT INTO majmin (id, name, type, classesNeeded) VALUES (50, 'Computational Science', 'minor', 'Introduction to Computational Science, Scientific Computing');